import Head from "next/head";
import { useState } from "react";
import { useAuthState } from "react-firebase-hooks/auth";
import styled from "styled-components";
import Layout from "../components/layout";
import firebase from "../firebase/clientApp";

const Button = styled.button`
  position: fixed;
  width: 200px;
  height: 200px;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  box-shadow: 0 2.5rem 2rem -2rem hsl(200 50% 20% / 40%);
  background: #fff;
  border-radius: 50%;
`;

export default function Home() {
  const [button, setButton] = useState(false);
  const [user, loading, error] = useAuthState(firebase.auth());

  const handleAttend = () => {
    const result = window.confirm("本当に出勤しますか？");
    if (result) {
      setButton(true);
      console.log("出勤しました");
    }
  };

  const handleLeaveWork = () => {
    const result = window.confirm("本当に退勤しますか？");
    if (result) {
      setButton(false);
      console.log("退勤しました");
    }
  };

  if (loading) return loading;
  if (error) return null;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {user && <p>{user.displayName}</p>}
        {button ? (
          <Button onClick={handleLeaveWork}>退勤する</Button>
        ) : (
          <Button onClick={handleAttend}>出勤する</Button>
        )}
      </Layout>
    </>
  );
}
